- hosts: redpanda

  tasks:
  - name: Copy CA Certs
    copy:
      src: ca/ca.crt
      dest: /etc/redpanda/certs/truststore.pem
      owner: redpanda
      group: redpanda

  - name: Copy Node Certs
    copy:
      src: certs/{{ansible_hostname}}/node.crt
      dest: /etc/redpanda/certs/node.crt
      owner: redpanda
      group: redpanda

  - name: Configure via RPK
    shell: |
      rpk redpanda config set redpanda.admin_api_tls '{
        enabled: true,
        require_client_auth: false,
        key_file: /etc/redpanda/certs/node.key,
        cert_file: /etc/redpanda/certs/node.crt,
        truststore_file: /etc/redpanda/certs/truststore.pem
      }' --format yaml

      rpk redpanda config set redpanda.kafka_api_tls '{
        enabled: true,
        require_client_auth: false,
        key_file: /etc/redpanda/certs/node.key,
        cert_file: /etc/redpanda/certs/node.crt,
        truststore_file: /etc/redpanda/certs/truststore.pem
      }' --format yaml

      rpk redpanda config set redpanda.rpc_server_tls '{
        enabled: true,
        require_client_auth: false,
        key_file: /etc/redpanda/certs/node.key,
        cert_file: /etc/redpanda/certs/node.crt,
        truststore_file: /etc/redpanda/certs/truststore.pem
      }' --format yaml

      rpk redpanda config set 'rpk.admin_api' "
        tls:
          truststore_file: /etc/redpanda/certs/truststore.pem
      " --format yaml

      rpk redpanda config set 'rpk.kafka_api.tls' "
          { truststore_file: /etc/redpanda/certs/truststore.pem }
      " --format yaml

      chown -R redpanda:redpanda /etc/redpanda

  - name: Restart redpanda
    systemd:
      name: redpanda
      state: restarted
