repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        files: '\.(yml|yaml)$'
      - id: end-of-file-fixer
        files: '\.(yml|yaml)$'
      - id: trailing-whitespace
        files: '\.(yml|yaml)$'
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.13.1
    hooks:
      - id: ansible-lint
        args: [ "-c", ".ansible-lint.yml" ]
        files: '\.(yml|yaml)$'
        language_version: python3
  #        exclude: ansible/prepare-data-dir.yml
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
        exclude: ibm|azure|gcp
      - id: terraform_validate
        exclude: ibm|azure|gcp
      - id: terraform_tflint
        args:
          - config=.tflint.hcl
        exclude: ibm|azure|gcp
exclude: ansible/roles/redpanda_broker/templates/(bootstrap|redpanda)\.yml
