---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        files: \.(yml|yaml)$
      - id: end-of-file-fixer
        files: \.(yml|yaml)$
      - id: trailing-whitespace
        files: \.(yml|yaml)$
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.14.2
    hooks:
      - id: ansible-lint
        args: [ "-c", ".ansible-lint" ]
        files: \.(yaml|yml)$
        entry: ansible-lint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1
    hooks:
      - id: terraform_fmt
        exclude: ibm|azure|gcp
      - id: terraform_validate
        exclude: ibm|azure|gcp
      - id: terraform_tflint
        args:
          - config=.tflint.hcl
        exclude: ibm|azure|gcp
exclude: ansible/roles/redpanda_broker/templates/(bootstrap|redpanda)\.yml
