FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive

ENV DA_AWS_ACCESS_KEY_ID="default"
ENV DA_AWS_SECRET_ACCESS_KEY="default"
ENV AWS_DEFAULT_REGION="default"
ENV GCP_CREDS="default"

# Install required packages
RUN apt-get update \
    && apt install -y unzip wget curl vim git software-properties-common awscli jq lsb-release gnupg \
    && apt-add-repository --yes --update ppa:ansible/ansible \
    && apt-get install -y ansible \
    && echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - \
    && apt-get update  \
    && apt-get install -y google-cloud-sdk \
    && rm -rf /var/lib/apt/lists/*


# Install Terraform
RUN wget https://releases.hashicorp.com/terraform/1.4.5/terraform_1.4.5_linux_amd64.zip \
    && unzip terraform_1.4.5_linux_amd64.zip -d /usr/local/bin \
    && rm terraform_1.4.5_linux_amd64.zip

# Install task
RUN curl -sSLf "https://github.com/go-task/task/releases/download/v3.21.0/task_linux_amd64.tar.gz" | tar -xz -C /usr/local/bin

## uncomment for use as a local client
#RUN mkdir -p /app
#COPY . /app

# Set the default command to run when the container starts
CMD ["/bin/bash"]
