FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive

ENV DA_AWS_ACCESS_KEY_ID="default"
ENV DA_AWS_SECRET_ACCESS_KEY="default"
ENV AWS_DEFAULT_REGION="default"
ENV GCP_CREDS="default"

# Install required packages
RUN apt-get update \
    && apt install -y unzip wget curl vim git software-properties-common awscli jq lsb-release gnupg make default-jdk \
    && apt-add-repository --yes --update ppa:ansible/ansible \
    && apt-get install -y ansible \
    && echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - \
    && apt-get update  \
    && apt-get install -y google-cloud-sdk \
    && rm -rf /var/lib/apt/lists/*


# Install Go
RUN ARCH=$(dpkg --print-architecture) \
    && GO_VERSION=1.23.5 \
    && wget "https://go.dev/dl/go${GO_VERSION}.linux-${ARCH}.tar.gz" \
    && tar -C /usr/local -xzf "go${GO_VERSION}.linux-${ARCH}.tar.gz" \
    && rm "go${GO_VERSION}.linux-${ARCH}.tar.gz"

ENV PATH="/usr/local/go/bin:${PATH}"

# Install Terraform
RUN ARCH=$(dpkg --print-architecture) \
    && if [ "$ARCH" = "amd64" ]; then TF_ARCH="amd64"; else TF_ARCH="arm64"; fi \
    && wget "https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_${TF_ARCH}.zip" \
    && unzip "terraform_1.7.4_linux_${TF_ARCH}.zip" -d /usr/local/bin \
    && rm "terraform_1.7.4_linux_${TF_ARCH}.zip"

# Install task
RUN ARCH=$(dpkg --print-architecture) \
    && if [ "$ARCH" = "amd64" ]; then TASK_ARCH="amd64"; else TASK_ARCH="arm64"; fi \
    && curl -sSLf "https://github.com/go-task/task/releases/download/v3.21.0/task_linux_${TASK_ARCH}.tar.gz" | tar -xz -C /usr/local/bin

## uncomment for use as a local client
#RUN mkdir -p /app
#COPY . /app

# Set the default command to run when the container starts
CMD ["/bin/bash"]
