FROM fedora:36

ENV DA_AWS_ACCESS_KEY_ID="default"
ENV DA_AWS_SECRET_ACCESS_KEY="default"
ENV AWS_DEFAULT_REGION="default"
ENV GCP_CREDS="default"

# Install required packages
RUN dnf -y update \
    && dnf install -y unzip wget glibc curl vim git ansible jq openssl \
    && dnf clean all \
    && rm -rf /var/cache/dnf/*

# Install Terraform
RUN wget https://releases.hashicorp.com/terraform/1.4.5/terraform_1.4.5_linux_amd64.zip \
    && unzip terraform_1.4.5_linux_amd64.zip -d /usr/local/bin \
    && rm terraform_1.4.5_linux_amd64.zip

# Install aws cli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip" \
&& unzip awscliv2.zip \
&& ./aws/install

RUN curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-448.0.0-linux-x86_64.tar.gz && \
    tar -zxvf google-cloud-cli-448.0.0-linux-x86_64.tar.gz && \
    ./google-cloud-sdk/install.sh --quiet && \
    rm google-cloud-cli-448.0.0-linux-x86_64.tar.gz

ENV PATH="/google-cloud-sdk/bin:${PATH}"

# Install task
RUN curl -sSLf "https://github.com/go-task/task/releases/download/v3.21.0/task_linux_amd64.tar.gz" | tar -xz -C /usr/local/bin

## uncomment for use as a local client
#RUN mkdir -p /app
#COPY . /app

# Set the default command to run when the container starts
CMD ["/bin/bash"]
