collections:
  - name: community.general
  - name: https://github.com/redpanda-data/redpanda-ansible-collection.git
    type: git
    version: console-config-changes
  - name: ansible.posix
  - name: grafana.grafana
    version: 5.6.0
  - name: prometheus.prometheus

roles:
  - src: mrlesmithjr.mdadm
  - src: mrlesmithjr.squid
  - src: geerlingguy.node_exporter
