collections:
  - name: community.general
  - name: https://github.com/redpanda-data/redpanda-ansible-collection.git
    type: git
    version: fix-sysctl-for-large-ssytems
  - name: ansible.posix
  - name: grafana.grafana

roles:
  - src: mrlesmithjr.mdadm
  - src: mrlesmithjr.squid
  - src: cloudalchemy.prometheus
  - src: geerlingguy.node_exporter
