agents:
  queue: "k8s-builders"

steps:
  - label: gcp ubuntu tiered
    key: tiered-up-gcp-ubuntu
    command: ./.buildkite/scripts/standup-gcp-cluster.sh --tf_dir "gcp" --image "ubuntu-os-cloud/ubuntu-2204-lts" --prefix "ci-ub-ts" --cluster_type "tiered-storage-cluster" --gcp_creds "$DEVEX_GCP_CREDS_BASE64" --tiered true
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DEVEX_GCP_CREDS_BASE64
  - label: gcp fedora tiered
    key: tiered-up-gcp-fedora
    command: ./.buildkite/scripts/standup-gcp-cluster.sh --tf_dir "gcp" --image "fedora-cloud/fedora-cloud-37" --prefix "ci-fd-ts" --cluster_type "tiered-storage-cluster" --gcp_creds "$DEVEX_GCP_CREDS_BASE64" --tiered true
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DEVEX_GCP_CREDS_BASE64
  - label: gcp ubuntu basic
    key: basic-up-gcp-ubuntu
    command: ./.buildkite/scripts/standup-gcp-cluster.sh --tf_dir "gcp" --image "ubuntu-os-cloud/ubuntu-2204-lts" --prefix "ci-ub-bs" --cluster_type "basic-cluster" --gcp_creds "$DEVEX_GCP_CREDS_BASE64" --tiered false
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DEVEX_GCP_CREDS_BASE64
  - label: gcp fedora basic
    key: basic-up-gcp-fedora
    command: ./.buildkite/scripts/standup-gcp-cluster.sh --tf_dir "gcp" --image "fedora-cloud/fedora-cloud-37" --prefix "ci-fd-bs" --cluster_type "basic-cluster" --gcp_creds "$DEVEX_GCP_CREDS_BASE64" --tiered false
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DEVEX_GCP_CREDS_BASE64
  - label: test basic cluster standup ubuntu
    key: basic-up-ubuntu
    command: .buildkite/scripts/standup-cluster.sh --prefix=rp-basic-ub --distro=ubuntu-focal --tiered=false --unstable=false --taskname=basic-cluster
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test tiered-storage-up cluster standup ubuntu
    key: tiered-up-ubuntu
    command: .buildkite/scripts/standup-cluster.sh --prefix=rp-tier-ub --distro=ubuntu-focal --tiered=true --unstable=false --taskname=tiered-storage-cluster
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test unstable tiered-storage-up cluster standup ubuntu
    key: tiered-up-unstable-ubuntu
    command: .buildkite/scripts/standup-cluster.sh --prefix=rp-un-tier-ub --distro=ubuntu-focal --tiered=true --unstable=true --taskname=tiered-storage-cluster
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test tiered-storage-up cluster standup fedora
    key: tiered-up-fedora
    command: .buildkite/scripts/standup-cluster.sh --prefix=rp-tier-fd --distro=Fedora-Cloud-Base-36 --tiered=true --unstable=false --taskname=tiered-storage-cluster
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test unstable tiered-storage-up cluster standup fedora
    key: tiered-up-unstable-fedora
    command: .buildkite/scripts/standup-cluster.sh --prefix=rp-un-tier-fd --distro=Fedora-Cloud-Base-36 --tiered=true --unstable=true --taskname=tiered-storage-cluster
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test tiered-storage-up cluster standup ubuntu with is4gen.4xlarge
    key: tiered-up-ubuntu-is4
    command: .buildkite/scripts/standup-cluster.sh --prefix=rp-tier-ub-is --distro=ubuntu-focal --tiered=true --unstable=false --taskname=tiered-storage-cluster --machinearch=arm64 --instancetype=is4gen.4xlarge
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test unstable tiered-storage-up cluster standup ubuntu with is4gen.4xlarge
    key: tiered-up-unstable-ubuntu-is4
    command: .buildkite/scripts/standup-cluster.sh --prefix=rp-un-tier-ub-is --distro=ubuntu-focal --tiered=true --unstable=true --taskname=tiered-storage-cluster --machinearch=arm64 --instancetype=is4gen.4xlarge
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test tiered-storage-up cluster standup fedora with is4gen.4xlarge
    key: tiered-up-fedora-is4
    command: .buildkite/scripts/standup-cluster.sh --prefix=rp-tier-fd-is --distro=Fedora-Cloud-Base-36 --tiered=true --unstable=false --taskname=tiered-storage-cluster --machinearch=arm64 --instancetype=is4gen.4xlarge
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test unstable tiered-storage-up cluster standup fedora with is4gen.4xlarge
    key: tiered-up-unstable-fedora-is4
    command: .buildkite/scripts/standup-cluster.sh --prefix=rp-un-tier-fd-is --distro=Fedora-Cloud-Base-36 --tiered=true --unstable=true --taskname=tiered-storage-cluster --machinearch=arm64 --instancetype=is4gen.4xlarge
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
