agents:
  queue: "k8s-builders"

steps:
  - label: gcp ubuntu tiered
    key: tiered-up-gcp-ubuntu
    command: ./.buildkite/scripts/standup-gcp-cluster.sh --tf_dir "gcp" --image "ubuntu-os-cloud/ubuntu-2204-lts" --prefix "ci-ub-ts" --cluster_type "tiered-storage-cluster" --gcp_creds "$DEVEX_GCP_CREDS_BASE64" --tiered true
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DEVEX_GCP_CREDS_BASE64
  - label: gcp fedora tiered
    key: tiered-up-gcp-fedora
    command: ./.buildkite/scripts/standup-gcp-cluster.sh --tf_dir "gcp" --image "fedora-cloud/fedora-cloud-37" --prefix "ci-fd-ts" --cluster_type "tiered-storage-cluster" --gcp_creds "$DEVEX_GCP_CREDS_BASE64" --tiered true
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DEVEX_GCP_CREDS_BASE64
  - label: gcp ubuntu basic
    key: basic-up-gcp-ubuntu
    command: ./.buildkite/scripts/standup-gcp-cluster.sh --tf_dir "gcp" --image "ubuntu-os-cloud/ubuntu-2204-lts" --prefix "ci-ub-bs" --cluster_type "basic-cluster" --gcp_creds "$DEVEX_GCP_CREDS_BASE64" --tiered false
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DEVEX_GCP_CREDS_BASE64
  - label: gcp fedora basic
    key: basic-up-gcp-fedora
    command: ./.buildkite/scripts/standup-gcp-cluster.sh --tf_dir "gcp" --image "fedora-cloud/fedora-cloud-37" --prefix "ci-fd-bs" --cluster_type "basic-cluster" --gcp_creds "$DEVEX_GCP_CREDS_BASE64" --tiered false
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DEVEX_GCP_CREDS_BASE64
  - label: test basic cluster standup ubuntu
    key: basic-up-ubuntu
    command: PREFIX="rp-basic-ub" DISTRO="ubuntu-focal" TIERED=false UNSTABLE=false TASK_NAME="basic-cluster" task integration-aws
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test tiered-storage-up cluster standup ubuntu
    key: tiered-up-ubuntu
    command: PREFIX="rp-tier-ub" DISTRO="ubuntu-focal" TIERED=true UNSTABLE=false TASK_NAME="tiered-storage-cluster" task integration-aws
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test unstable tiered-storage-up cluster standup ubuntu
    key: tiered-up-unstable-ubuntu
    command: PREFIX="rp-un-tier-ub" DISTRO="ubuntu-focal" TIERED=true UNSTABLE=true TASK_NAME="tiered-storage-cluster" task integration-aws
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test tiered-storage-up cluster standup fedora
    key: tiered-up-fedora
    command: PREFIX="rp-tier-fd" DISTRO="Fedora-Cloud-Base-36" TIERED=true UNSTABLE=false TASK_NAME="tiered-storage-cluster" task integration-aws
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test unstable tiered-storage-up cluster standup fedora
    key: tiered-up-unstable-fedora
    command: PREFIX="rp-un-tier-fd" DISTRO="Fedora-Cloud-Base-36" TIERED=true UNSTABLE=true TASK_NAME="tiered-storage-cluster" task integration-aws
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test tiered-storage-up cluster standup ubuntu with is4gen.4xlarge
    key: tiered-up-ubuntu-is4
    command: PREFIX="rp-tier-ub-is" DISTRO="ubuntu-focal" TIERED=true UNSTABLE=false TASK_NAME="tiered-storage-cluster" MACHINE_ARCH="arm64" INSTANCE_TYPE="is4gen.4xlarge" task integration-aws
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test unstable tiered-storage-up cluster standup ubuntu with is4gen.4xlarge
    key: tiered-up-unstable-ubuntu-is4
    command: PREFIX="rp-un-tier-ub-is" DISTRO="ubuntu-focal" TIERED=true UNSTABLE=true TASK_NAME="tiered-storage-cluster" MACHINE_ARCH="arm64" INSTANCE_TYPE="is4gen.4xlarge" task integration-aws
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test tiered-storage-up cluster standup fedora with is4gen.4xlarge
    key: tiered-up-fedora-is4
    command: PREFIX="rp-tier-fd-is" DISTRO="Fedora-Cloud-Base-36" TIERED=true UNSTABLE=false TASK_NAME="tiered-storage-cluster" MACHINE_ARCH="arm64" INSTANCE_TYPE="is4gen.4xlarge" task integration-aws
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test unstable tiered-storage-up cluster standup fedora with is4gen.4xlarge
    key: tiered-up-unstable-fedora-is4
    command: PREFIX="rp-un-tier-fd-is" DISTRO="Fedora-Cloud-Base-36" TIERED=true UNSTABLE=true TASK_NAME="tiered-storage-cluster" MACHINE_ARCH="arm64" INSTANCE_TYPE="is4gen.4xlarge" task integration-aws
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test large unstable tiered-storage-up cluster standup fedora with im4gn.8xlarge
    key: large-up-unstable-fedora-is4
    command: NUM_NODES=5 PREFIX="rp-un-lrg-fd-im4-x8" AZ_STRING="us-east-1a,us-east-1b,us-east-1c" AWS_REGION="us-east-1" DISTRO="Fedora-Cloud-Base-36" TIERED=true UNSTABLE=true TASK_NAME="tiered-storage-cluster" MACHINE_ARCH="arm64" INSTANCE_TYPE="im4gn.8xlarge" task integration-aws
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test large unstable tiered-storage-up cluster standup ubuntu with im4gn.8xlarge
    key: large-up-unstable-ubuntu-is4
    command: NUM_NODES=5 PREFIX="rp-un-lrg-im4-x8" AZ_STRING="us-east-2a,us-east-2b,us-east-2c" AWS_REGION="us-east-2" DISTRO="ubuntu-focal" TIERED=true UNSTABLE=true TASK_NAME="tiered-storage-cluster" MACHINE_ARCH="arm64" INSTANCE_TYPE="im4gn.8xlarge" task integration-aws
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION