---
# attempt to do a rolling, serial restart by putting each node into maintenance
# mode, restarting, and putting it back into service. This is throttled to allow
# only one node out of service at a time.
#
- name: Enable Maintenance Mode
  ansible.builtin.command:
    cmd: rpk cluster maintenance enable {{ node_id }} --wait {{ redpanda_rpk_opts }}
  no_log: true
  when:
    - restart_required
    - inventory_hostname == cluster_host

# We need to (actually) generate the node config once the node is in MM, otherwise the `rpk cluster maintenance` command
# will fail
- name: Generate Node config - post-bootstrap runs
  ansible.builtin.template:
    src: redpanda.yml
    dest: /etc/redpanda/redpanda.yaml
    owner: redpanda
    group: redpanda
    mode: "0755"
  register: nodeconfig_result
  when:
    - is_initialized
    - inventory_hostname == cluster_host

- name: Restart Redpanda
  ansible.builtin.systemd:
    name: redpanda
    state: restarted
  when:
    - restart_required
    - inventory_hostname == cluster_host

- name: Disable Maintenance Mode
  ansible.builtin.command:
    cmd: rpk cluster maintenance disable {{ node_id }} {{ redpanda_rpk_opts }}
  no_log: true
  when:
    - restart_required
    - inventory_hostname == cluster_host
