- include: install-node-deps.yml

- include: prepare-data-dir.yml

- include: install-redpanda.yml

- include: start-redpanda.yml
  when: start | default(False)

- include: deploy-prometheus-grafana.yml
  when: start | default(False)
