---
- name: install_certs - Copy CA Certs
  tags:
    - install_certs
  copy:
    src: tls/ca/ca.crt
    dest: "{{ redpanda_truststore_file }}"
    owner: redpanda
    group: redpanda
    force: "{{ overwrite_certs | default('no') | bool }}"

- name: install_certs - Copy Node Certs
  tags:
    - install_certs
  copy:
    src: tls/certs/{{ansible_hostname}}/node.crt
    dest: "{{ redpanda_cert_file }}"
    owner: redpanda
    group: redpanda
    force: "{{ overwrite_certs | default('no') | bool }}"

- name: install_certs - Set Redpanda config
  tags:
    - install_certs
  set_fact:
    tls: true

- name: install_certs - Apply updated config via reapplying the redpanda_broker role
  tags: install_certs
  import_role:
    name: redpanda_broker
  when: not skip_node | default(false) | bool
