---
- name: Bundle debs
  hosts: client
  vars:
    basearch: "amd64" # must match the output of `uname -m`. however on ubuntu you need to use the debian version of the output. So for example x86_64 is amd64
    os_distribution_major_version: "focal" # must match the output of `. /etc/os-release && echo ${VERSION_ID%%.*}`
    os_distribution: "ubuntu" # must match the output of `. /etc/os-release && echo $ID`
    redpanda_version: "23.1.13-1" # note that the -1 is the build number for this version. it is typically -1 but if the version is incremented it will be higher
    rpm_or_deb: "deb"
  tasks:
    - name: Bundle debs for airgap
      ansible.builtin.include_role:
        name: redpanda.cluster.binary_bundler
      run_once: true
