exclude_paths:
  - .github/
  - artifacts/
  - aws/
  - azure/
  - gcp/
  - ibm/
  - templates/

enable_list:
  - yaml
  - empty-string-compare
  - args

profile: production

mock_modules:
  - ansible.posix.filesystem
  - ansible.posix.authorized_key
  - ansible.posix.mount
