# jmespath is a required dependency for this playbook. Install it with `pip install jmespath`.
- name: Set node_exporter_arch based on host architecture
  hosts: redpanda
  tasks:
    - name: Set node_exporter_arch based on host architecture
      ansible.builtin.set_fact:
        rp_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"
    - name: Include geerlingguy nodeexporter
      ansible.builtin.include_role:
        name: geerlingguy.node_exporter
      vars:
        node_exporter_arch: "{{ rp_arch }}"

- name: Install jmespath
  hosts: monitor
  tasks:
    - name: Install deps
      ansible.builtin.package:
        name: python3-jmespath
        state: present

- name: Install prometheus
  hosts: monitor
  roles:
    - prometheus.prometheus.prometheus
  vars:
    prometheus_scrape_configs:
      - job_name: "redpanda"
        metrics_path: "/public_metrics"
        static_configs:
          - targets: "{{ groups['redpanda'] | default([]) | map('extract', hostvars, 'inventory_hostname') | map('regex_replace', '^(.*)$','\\1:9644') | list  }}"
      - job_name: "node"
        metrics_path: "/metrics"
        static_configs:
          - targets: "{{ groups['redpanda'] | default([]) | map('extract', hostvars, 'inventory_hostname') | map('regex_replace', '^(.*)$','\\1:9100') | list  }}"
      - job_name: "connect"
        metrics_path: "/metrics"
        static_configs:
          - targets: "{{ groups['connect'] | default([]) | map('extract', hostvars, 'inventory_hostname') | map('regex_replace', '^(.*)$','\\1:9404') | list  }}"

- name: Install grafana
  hosts: monitor
  roles:
    - grafana.grafana.grafana
  vars:
    grafana_version: 10.4.1
    grafana_security:
      admin_user: admin
      admin_password: "{{ grafana_admin_pass | default('enter_your_secure_password', true) }}"
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://localhost:9090'
        basicAuth: false
    grafana_dashboards:
      - dashboard_id: 1860
        revision_id: 31
        datasource: prometheus
      - dashboard_id: 7496
        revision_id: 1
        datasource: prometheus
      - dashboard_id: 18135
        revision_id: 1
        datasource: prometheus
