- name: Install redpanda-connect and set up systemd service
  hosts: connect
  become: true

  vars:
    rpcn_dir: /etc/redpanda
    local_files_dir: "./rpcn_files"   # directory on your control machine to upload

  pre_tasks:
    - name: Set package script location for Debian/Ubuntu
      set_fact:
        download_url: "https://dl.redpanda.com/nzc4ZYQK3WRGd9sy/redpanda/cfg/setup/bash.deb.sh"
      when: ansible_facts['os_family'] == "Debian"

    - name: Set package script location for RHEL-family
      set_fact:
        download_url: "https://dl.redpanda.com/nzc4ZYQK3WRGd9sy/redpanda/cfg/setup/bash.rpm.sh"
      when: ansible_facts['os_family'] == "RedHat"


  tasks:
    # --- Ensure target directory exists before unarchive ---
    - name: Ensure /etc exists
      file:
        path: /etc
        state: directory
        mode: "0755"

    - name: Ensure target directory exists
      file:
        path: "{{ rpcn_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Verify target directory exists
      stat:
        path: "{{ rpcn_dir }}"
      register: rpcn_dir_stat

    - name: Fail if target directory is missing
      fail:
        msg: "Target directory {{ rpcn_dir }} was not created"
      when: not rpcn_dir_stat.stat.exists

    # --- Install redpanda-connect package ---
    - name: dnf install redpanda-connect
      ansible.builtin.dnf:
        name: redpanda-connect
        state: present
      when: ansible_facts['os_family'] == "RedHat"
    
    - name: apt install redpanda-connect
      ansible.builtin.apt:
        name: redpanda-connect
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"   

    # --- Copy your local files to the REMOTE host(s) ---
    - name: Copy your local files into /etc/redpanda (recursive)
      copy:
        src: "{{ local_files_dir }}/"
        dest: "{{ rpcn_dir }}/"
        owner: root
        group: root
        mode: "0644"

    # --- Install systemd unit ---
    - name: Copy service file from /etc/redpanda to systemd unit dir
      copy:
        src: "{{ rpcn_dir }}/rpcn.service"
        dest: /etc/systemd/system/rpcn.service
        owner: root
        group: root
        mode: "0644"
        remote_src: true
      notify: daemon-reload

    - name: Enable and start rpcn service
      systemd:
        name: rpcn.service
        enabled: true
        state: started

  handlers:
    - name: daemon-reload
      systemd:
        daemon_reload: true



