name: ansible-lint
on: [pull_request]

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install ansible && pip install ansible-lint

      - name: Run Ansible Linter
        run: |
          ansible-galaxy install -r ansible/requirements.yml
          ansible-lint -c .config/ansible-lint.yml
