name: ansible-lint
on: [ pull_request ]

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ansible Lint
        uses: ansible/ansible-lint@main
